### ISSUE TITLE
C# dotnet core support

### ISSUE THREAD

**Issue by khwong9981** [ShiftLeftSecurity/shiftleft-scan-vscode#32]
How can I scan c# dotnet core project in VS code? I am getting below error when start scan and not sure how can proceed?

Scanning C# and .Net core projects is only possible with ShiftLeft NG SAST. To enable visit                             
                    [4;94mhttps://www.shiftleft.io/register[0m to signup and pass the tokens as environment variables!

**Comment by prabhu** [comment]
Hi @khwong9981 There is no c# support in the open source tool. You can try our commercial platform called NG SAST https://www.shiftleft.io/register if you are interested.
