### ISSUE TITLE
scan: illegal option -- -

### ISSUE THREAD

**Issue by jimsmith-fd** [ShiftLeftSecurity/shiftleft-scan-vscode#34]
⚡︎ Security scan has started ...
/bin/bash scan --src /Users/jim.smith/code-repo --mode ide
scan: illegal option -- -
Type scan -h for usage info

Docker desktop is installed and running.
![image](https://user-images.githubusercontent.com/77489703/110100940-e4ae5d00-7d9a-11eb-9f36-bbadb2a1e012.png)

![image](https://user-images.githubusercontent.com/77489703/110100710-a1ec8500-7d9a-11eb-9c49-c938f790a2cc.png)

VSCode 1.54.1
```
Version: 1.54.1
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:42:18.719Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

**Comment by jimsmith-fd** [comment]
This seems an issue with your extension not detecting Docker Desktop (as other VS Code extensions work happily with Docker Desktop)

When I ran the above command, just so happens `scan` that executes is part of AVG Anti Virus:

```
which scan
/usr/local/bin/scan
lrwxr-xr-x  1 root  admin  58 25 Sep 08:52 /usr/local/bin/scan -> /Applications/AVGAntivirus.app/Contents/Backend/utils/scan
```

What would you suggest to get this working, as Checkov works perfectly fine in VSCode which runs as a docker container.

**Comment by jimsmith-fd** [comment]
@prabhu  bump

**Comment by jimsmith** [comment]
No and I would never remove any A/V tooling for likes of upgrades of any A/V vendor.

**Comment by prabhu** [comment]
it is removing a symlink not uninstalling. I can treat this ticket as an enhancement and try some fixes

**Comment by jimsmith** [comment]
fundamentally it doesn't work but hey I'll continue to use checkov and other security tools out there :)

**Comment by prabhu** [comment]
https://github.com/ShiftLeftSecurity/shiftleft-scan-vscode/blob/master/src/Scan.ts#L75

I introduced a change to check if scan is available locally to support Visual Studio Codespace and even AppImage. It checks for a local command named `scan`. In your case, it exists but is unfortunately a symlink to an antivirus. The fix is to change the word `scan` here to `slscan` - https://github.com/ShiftLeftSecurity/shiftleft-scan-vscode/blob/master/src/Scan.ts#L80

Will you be interested in sending a PR?

**Comment by prabhu** [comment]
@jimsmith-fd Version 1.3.0 has been released which uses the new command for any local invocations. If you update the extension things should start working nicely for you!
